//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GCNLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GCNLibrary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # KCL Flags
        ///camera_id
        ///Sound_code
        ///Floor_code
        ///Wall_code
        ///Camera_through
        ///
        ///# orientation
        ///pos_x
        ///pos_y
        ///pos_z
        ///
        ///dir_x
        ///dir_y
        ///dir_z
        ///
        ///scale_x
        ///scale_y
        ///scale_z
        ///
        ///# identification
        ///name
        ///dmd_name
        ///path_name
        ///create_name
        ///character_name
        ///access_name
        ///CodeName
        ///
        ///# generic arguments
        ///arg0
        ///arg1
        ///arg2
        ///arg3
        ///arg4
        ///arg5
        ///arg6
        ///arg7
        ///arg8
        ///
        ///# point
        ///pnt0_x
        ///pnt0_y
        ///pnt0_z
        ///
        ///# furniture
        ///furniture_x
        ///furniture_y
        ///furniture_z
        ///
        ///# unsorted
        ///poly_material
        ///use
        ///hashigo
        ///appear_flag
        ///disappear_flag
        ///event_set_no
        ///stay
        ///room_no
        ///OpenDoorNo
        ///appear_percent
        ///type
        ///invisible [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Hashes {
            get {
                return ResourceManager.GetString("Hashes", resourceCulture);
            }
        }
    }
}
